### PR TITLE
Remove bootstrap

### PR DESCRIPTION
**Pull request by 4194304**
Works completely as intended, mobile menu is unstable though and needs further fixing. Should be fine to commit if I work on it tomorrow

### CODE REVIEW

**Comment by SolDev69** [comment]
No one merge this, I need to look this over.

**Comment by SolDev69** [comment]
Scaling is wonky

**Comment by SolDev69** [comment]
Mobile menu doesn't work if you are scrolled down the page

**Comment by SolDev69** [comment]
The site is also completely broken on Edge

**Comment by SolDev69** [comment]
Update: not broken on edge, flatpak just has skill issue

**Comment by 4194304** [comment]
menu should work as intended, commit #8 should fix off-centered text

**Comment by 4194304** [comment]
fixed off-centered menu text

**Pull request closed without merging**
