### PR TITLE
Rewrite in SvelteKit

### PR DESCRIPTION
**Pull request by code913**
The current pure HTML code is ultra hard to maintain because you need to manually copy paste all reused stuff to each file e.g. the header. I chose Svelte because it produces 0 javascript if your component doesn't need it, thus it should have the same performance and bundle size as the original HTML code.

I'm also switching the design system from bootstrap [to material design](https://material-web.dev) because it's better; this fixes #11.

### CODE REVIEW

**Comment by SolDev69** [comment]
Hi

**Comment by SolDev69** [comment]
uhhh

**Comment by SolDev69** [comment]
Wtf is sveltekit

**Comment by code913** [comment]
This PR can be merged now, just need to do a bit of cleanup to remove unnecessary files

**Comment by code913** [comment]
> Wtf is sveltekit

https://kit.svelte.dev  
REALLY good back-end framework for svelte, just like NextJS

**Comment by SolDev69** [comment]
I would heavily prefer not having any nodejs components here

**Comment by SolDev69** [comment]
How the fuck do I even test this?

**Comment by code913** [comment]
> I would heavily prefer not having any nodejs components here

almost no javascript here, there is just the javascript for hiding and showing the navbar on mobile when you click the menu button  

there were some {#each} tags with javascript but i removed them

**Comment by code913** [comment]
> How the fuck do I even test this?

https://redesigned-invention-q4v99qgx5gvfrwg-5173.app.github.dev/

**Comment by SolDev69** [comment]
I do not understand what any of this is

**Comment by code913** [comment]
> I do not understand what any of this is

- anything in `static` directory is just served as is, e.g. the mod zip files and the favicon for the website
- any `+page.svelte` file in `src/routes` directory defines the page for that route, e.g. `src/routes/downloads/+page.svelte` corresponds to `/downloads` page
- the `Header.svelte` file is the code for the header at the top of every page
- the `+layout.svelte` file is a wrapper for code that runs on every page, e.g. i put the header in the file so it shows on every page
that's kinda it, the only javascript needed is to toggle showing/hiding the links in the header

**Comment by code913** [comment]
deploying to github pages is automatically done by the `.github/workflows/deploy.yml` file when you merge this pull request or commit anything to `main` branch

**Comment by code913** [comment]
these files are just generated by svelte or npm, they don't really need to be touched apart from that i added the adapter for github pages so it deploys correctly:
- `package.json`
- `package-lock.json`
- `vite.config.js`
- `svelte.config.js`

**Comment by SolDev69** [comment]
I'll be checking this over myself. No one merge this. I need to understand what this code does before I can confidently merge it.

**Comment by code913** [comment]
> I'll be checking this over myself. No one merge this. I need to understand what this code does before I can confidently merge it.

sure

**Comment by SolDev69** [comment]
add the light mode option you was talking about and I'll merge this

**Comment by SolDev69** [comment]
ykw I'ma just merge this

**Pull request merged**
